# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBDGqowg2x_WeRphGis5nStBpKczC4ca
"""

import streamlit as st
import pandas as pd
import joblib

# --- 1. ตั้งค่าหน้าตาแอป ---
st.set_page_config(page_title="California Housing Predictor", page_icon="🏠")

# --- 2. โหลด Full Pipeline (ตัวนี้สำคัญที่สุด) ---
@st.cache_resource
def load_pipeline():
    # โหลดไฟล์ pipeline ที่รวมทั้ง StandardScaler และ OneHotEncoder ไว้แล้ว
    return joblib.load('full_pipeline.pkl')

@st.cache_resource
def load_model():
    # โหลดตัวโมเดล XGBoost
    return joblib.load('xgboost_house_price_model.pkl')

try:
    pipeline = load_pipeline()
    model = load_model()
except Exception as e:
    st.error(f"❌ โหลดไฟล์ไม่สำเร็จ: {e}")
    st.stop()

# --- 3. UI รับข้อมูล ---
st.title("🏠 ระบบประเมินราคาที่พักอาศัย")
st.sidebar.header("📍 ระบุข้อมูล")

with st.sidebar:
    longitude = st.number_input("Longitude", value=-122.23)
    latitude = st.number_input("Latitude", value=37.88)
    housing_median_age = st.number_input("อายุบ้าน", value=30)
    total_rooms = st.number_input("ห้องทั้งหมด", value=800)
    total_bedrooms = st.number_input("ห้องนอนทั้งหมด", value=130)
    population = st.number_input("ประชากร", value=320)
    households = st.number_input("ครัวเรือน", value=120)
    median_income = st.number_input("รายได้เฉลี่ย", value=8.3)
    ocean_proximity = st.selectbox("ทำเล", ['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'])

# --- 4. ปุ่มคำนวณ ---
if st.button("🚀 คำนวณราคา"):
    # สร้าง DataFrame 12 คอลัมน์ตามที่ Pipeline ใน Colab ของคุณเคยได้รับ
    input_df = pd.DataFrame([[
        longitude, latitude, housing_median_age, total_rooms,
        total_bedrooms, population, households, median_income,
        (total_rooms / households), (total_bedrooms / total_rooms), (population / households),
        ocean_proximity
    ]], columns=[
        'longitude', 'latitude', 'housing_median_age', 'total_rooms',
        'total_bedrooms', 'population', 'households', 'median_income',
        'rooms_per_household', 'bedrooms_per_room', 'population_per_household',
        'ocean_proximity'
    ])

    try:
        # ขั้นตอนสำคัญ:
        # 1. ใช้ pipeline แปลงร่างข้อมูลจาก 12 -> 16 คอลัมน์
        X_prepared = pipeline.transform(input_df)

        # 2. ใช้โมเดล XGBoost ทำนายจากข้อมูลที่เตรียมเสร็จแล้ว
        prediction = model.predict(X_prepared)[0]

        st.balloons()
        st.success(f"### 🎉 ราคาประเมิน: ${prediction:,.2f}")

    except Exception as e:
        st.error(f"⚠️ เกิดข้อผิดพลาด: {e}")